### ISSUE TITLE
Crashes iOS app

### ISSUE THREAD

**Issue by nachofregeiro** [Wraptime/react-native-get-real-path#3]
It crashes trying to run the app on iOS. 

Can you check if GRP is defined in GRP.common.js line 14 to avoid this issue?

Replace line:
**var _getRealPathFromURI = Promise.promisify(GRP.getRealPathFromURI);**

with:
**var _getRealPathFromURI = Promise.promisify(GRP ? GRP.getRealPathFromURI : (fileUri)=>{ return fileUri; });**

Thanks!

**Comment by anton6** [comment]
Can you do a PR for this please? Thanks

**Comment by anton6** [comment]
Thanks for PR #4
