### ISSUE TITLE
RNGRPPackage.java not compiling for rn >= 0.47

### ISSUE THREAD

**Issue by MaxLarue** [Wraptime/react-native-get-real-path#9]
Function public List<Class<? extends JavaScriptModule>> createJSModules()  is deprecated since rn >= 0.47
Removing @Override solves the problem

**Comment by MaxLarue** [comment]
Issue solved but version on npm still has it

**Comment by anton6** [comment]
@MaxLarue Hi, can you please make a quick PR for this? thanks

**Comment by MaxLarue** [comment]
Hello
Inspecting the code on the repo the issue is already fixed
But when i npm install i get an install in which it is not, i think this
has to do with npm installing a previous version or that you'd have to make
a new release to publify the fix
Anyway the code on the repo already reflects the changes i intended to make
Installing directly from repo works out of the box
Thanks for the lib!
